# Generated by Django 4.0.6 on 2022-09-03 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashionStore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressbook',
            name='order',
        ),
    ]
