# Generated by Django 4.0.6 on 2022-09-03 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fashionStore', '0002_remove_addressbook_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbook',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fashionStore.order'),
        ),
    ]
