# Generated by Django 4.0.6 on 2022-08-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionStore', '0003_category_city_customer_order_state_whishlist_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribe',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='i want to recieve fashionStore Newsletter'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transction_id',
            field=models.CharField(default='9406899093', max_length=20, unique=True),
        ),
    ]
