# Generated by Django 4.0.6 on 2022-09-08 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fashionStore', '0005_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_orders', models.ManyToManyField(blank=True, null=True, to='fashionStore.order')),
            ],
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fashionStore.order'),
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
