# Generated by Django 4.0.6 on 2022-09-09 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fashionStore', '0006_usersorder_remove_orderitem_order_orderitem_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='UserOrder_product/')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('desc', models.TextField(max_length=255)),
                ('user_orders', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fashionStore.order')),
            ],
        ),
        migrations.DeleteModel(
            name='UsersOrder',
        ),
    ]
