# Generated by Django 4.0.6 on 2022-08-26 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fashionStore', '0006_alter_order_transction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='WhishList',
        ),
        migrations.AddField(
            model_name='whishlist',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fashionStore.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transction_id',
            field=models.CharField(default='2856831045', max_length=20, unique=True),
        ),
    ]
