# Generated by Django 4.0.6 on 2022-09-09 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fashionStore', '0007_usersorderitem_delete_usersorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersorderitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fashionStore.profile'),
        ),
    ]
