# Generated by Django 4.0.6 on 2022-08-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionStore', '0007_remove_product_whishlist_whishlist_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whishlist',
            name='customer',
        ),
        migrations.AlterField(
            model_name='order',
            name='transction_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
