# Generated by Django 4.0.6 on 2022-09-09 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashionStore', '0008_usersorderitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscribe',
        ),
    ]
