# Generated by Django 4.0.6 on 2022-08-26 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashionStore', '0009_city_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city',
            new_name='State',
        ),
    ]
