# Generated by Django 4.0.6 on 2022-08-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionStore', '0010_rename_city_city_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='fashionStore.category'),
        ),
    ]
