# Generated by Django 4.0.6 on 2022-08-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionStore', '0011_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.BooleanField(blank=True, choices=[('standard door delivery', 'standard door delivery'), ('Pickup Station', 'Pickup Station')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.BooleanField(blank=True, choices=[('Pay on delivery', 'on delivery'), ('with Card', 'with Card')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='transction_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
