# Generated by Django 4.0.6 on 2022-08-27 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fashionStore', '0012_alter_order_delivery_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whishlist',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fashionStore.customer'),
        ),
    ]
