# Generated by Django 4.0.6 on 2022-08-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionStore', '0016_alter_orderitem_quantity_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressbook',
            name='Street_address',
        ),
        migrations.AddField(
            model_name='addressbook',
            name='Address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='addressbook',
            name='City',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
