# Generated by Django 4.0.6 on 2022-08-28 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionStore', '0017_remove_addressbook_street_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressbook',
            old_name='Address',
            new_name='Additional_information',
        ),
        migrations.RenameField(
            model_name='addressbook',
            old_name='State',
            new_name='Region',
        ),
        migrations.AddField(
            model_name='addressbook',
            name='Delivery_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='addressbook',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='addressbook',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='addressbook',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{8,11}$')]),
        ),
        migrations.AlterField(
            model_name='addressbook',
            name='zip_code',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
