# Generated by Django 4.0.6 on 2022-08-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionStore', '0018_rename_address_addressbook_additional_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(choices=[(None, 'Please Select')], max_length=200),
        ),
    ]
