# Generated by Django 4.0.6 on 2022-08-28 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashionStore', '0020_alter_addressbook_region'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddressBook',
        ),
    ]
