# Generated by Django 4.0.6 on 2022-08-28 15:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fashionStore', '0021_delete_addressbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='AddressBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{8,11}$')])),
                ('City', models.CharField(blank=True, max_length=255, null=True)),
                ('Delivery_address', models.CharField(blank=True, max_length=255, null=True)),
                ('Additional_information', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=17, null=True)),
                ('default_address', models.BooleanField(blank=True, default=True, null=True)),
                ('Region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fashionStore.state')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fashionStore.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fashionStore.order')),
            ],
        ),
    ]
