# Generated by Django 4.0.6 on 2022-08-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionStore', '0022_alter_state_name_addressbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbook',
            name='Region',
            field=models.CharField(blank=True, choices=[(None, 'Please Select'), ('Delta', 'Delta'), ('Lagos', 'Lagos'), ('Abuja', 'Abuja'), ('Kano', 'Kano'), ('Rivers', 'Rivser'), ('Jos', 'Jos'), ('Sokoto', 'Sokoto')], max_length=255, null=True),
        ),
    ]
