# Generated by Django 4.0.6 on 2022-08-28 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashionStore', '0023_alter_addressbook_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressbook',
            options={'ordering': ['Delivery_address']},
        ),
    ]
