# Generated by Django 4.0.6 on 2022-08-28 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashionStore', '0024_alter_addressbook_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='city',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
